name: Endor Labs Dependency and Secrets Scan
on:
  pull_request:
    branches: [ main ]
jobs:
  endor-pr-scan:
    permissions:
      contents: read # Used to check out a private repository
      id-token: write # Used for keyless authentication with Endor Labs
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      ENDOR_API: https://api.endorlabs.com
      ENDOR_NAMESPACE: leonardo-learn
      ENDOR_PR_ID: ${{ github.event.pull_request.number }}
      ENDOR_SCM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENDOR_API_KEY: ${{ secrets.ENDOR_API_KEY }}
      ENDOR_API_SECRET: ${{ secrets.ENDOR_API_SECRET }}
      FAKE_MAVEN_PASSWORD: ${{ secrets.FAKE_GITHUB_PAT }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
        cache: maven
    - name: Build Package
      run: mvn clean install
    - name: Download endorctl
      run: |
        echo "Downloading latest endorctl"
        curl -sSL "$ENDOR_API/download/latest/endorctl_linux_amd64" -o endorctl
        echo "$(curl -s $ENDOR_API/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c -
        chmod +x ./endorctl
    - name: Run Endor Labs PR scan (incremental)
      id: endor_scan
      run: |
        ./endorctl scan --secrets \
          --namespace "$ENDOR_NAMESPACE" \
          --api-key "$ENDOR_API_KEY" \
          --api-secret "$ENDOR_API_SECRET" \